### ISSUE TITLE
Random spawning location

### ISSUE THREAD

**Issue by Dzierzan** [Dzierzan/OpenSA#13]
In the original game, antholes or neutral turrets (popcorn, thorn...) can be spawned everywhere apart from water tiles. Currently OpenRA doesn't support such behaviour.

**Comment by PaweX** [comment]
Maybe this issue should be pushed to OpenRA project, because I remember in Red Alert there was a whirlpool that was appearing in a random position of a map. However whirlpool could be spawned everywhere. The function should be updated with flags like: don't spawn on objects, don't spawn on water etc.

**Comment by Dzierzan** [comment]
Maybe it should but i doubt anyone will help.
